
INSERT INTO CUSTOMER(CUS_NAME, CUS_CITY, CUS_GRADE, CUST_GENDER)
VALUES ("Andile Thomas", "East London", 200, "Male");

SELECT * FROM CUSTOMER WHERE CUS_GRADE=100 OR CUS_GRADE=300;

UPDATE CUSTOMER SET CUS_GRADE=100 WHERE CUST_ID = 3009;
SELECT * FROM CUSTOMER ORDER BY CUST_ID ASC;

DROP TABLE CUSTOMER;

