version: "3.9"
services:
  redis:
    image: redis:6.2.7-alpine
    container_name: rediscontainer
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      - internalnet
networks:
  internalnet:
    driver: bridge
volumes:
  redis_data:
    external: false
